import type { Metadata } from "next";

import { Space_Grotesk } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import { Backdrop } from "./_components/backdrop";

const akshatSans = localFont({
  src: "./fonts/AkshatSans.ttf",
  display: "swap",
  variable: "--font-akshat-sans",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Akshat Adsule",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${akshatSans.variable} ${spaceGrotesk.variable} antialiased`}
    >
      <body className="bg-slate-900 leading-relaxed text-slate-400 antialiased selection:bg-teal-300 selection:text-teal-900">
        <div className="group/spotlight relative">
          <Backdrop />
          {children}
        </div>
      </body>
    </html>
  );
}
